[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mpacklog"
readme = "README.md"
authors = [
    {name = "Stéphane Caron", email = "stephane.caron@normalesup.org"},
]
maintainers = [
    {name = "Stéphane Caron", email = "stephane.caron@normalesup.org"},
]
dynamic = ['version', 'description']
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "aiofiles >= 0.7.0",
    "loop-rate-limiters >= 1.0.0",
    "msgpack >= 1.0.2",
]
keywords = ["messagepack", "serialization", "logging"]

[project.scripts]
mpacklog = "mpacklog.cli:main"

[project.urls]
Homepage = "https://github.com/stephane-caron/mpacklog.py"
Source = "https://github.com/stephane-caron/mpacklog.py"
Tracker = "https://github.com/stephane-caron/mpacklog.py/issues"
Changelog = "https://github.com/stephane-caron/mpacklog.py/blob/master/CHANGELOG.md"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I001",
    # pydocstyle
    "D"
]
ignore = [
    "D401",  # good for methods but not for class docstrings
    "D405",  # British-style section names are also "proper"!
]
pydocstyle = { convention = "google" }
