name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up Pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0

            - name: "Install coveralls"
              run: |
                  pip install coveralls

            - name: "Check code coverage"
              run: |
                  pixi run -e coverage coverage

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  coveralls --service=github --rcfile=pyproject.toml

    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0

            - name: "Check code format"
              run: |
                  pixi run -e lint lint

    test:
        name: "Test with ${{ matrix.pyenv }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                pyenv: [py39, py310, py311, py312]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0

            - name: "Run tests"
              run: |
                  pixi run -e test-${{ matrix.pyenv }} test

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [coverage, lint, test]
        steps:
            - run: echo "CI workflow completed successfully"
